#ifndef URG3D_ERRNO_H
#define URG3D_ERRNO_H

/*!
  \file
  \brief Error code

  \author Satofumi KAMIMURA

  $Id$
*/

enum {
    URG3D_NO_ERROR = 0,
    URG3D_UNKNOWN_ERROR = -1,
    URG3D_NOT_CONNECTED = -2,
    URG3D_NOT_IMPLEMENTED = -3,
    URG3D_INVALID_RESPONSE = -4,
    URG3D_NO_RESPONSE = -5,

    URG3D_SEND_ERROR = -6,
    URG3D_RECEIVE_ERROR = -7,
    URG3D_CHECKSUM_ERROR = -8,
    URG3D_INVALID_PARAMETER = -9,
    URG3D_MEASUREMENT_TYPE_MISMATCH = -10,
    URG3D_COMMON_ERROR_LAST,

    URG3D_SERIAL_OPEN_ERROR = (URG3D_COMMON_ERROR_LAST -1) -1,
    URG3D_NOT_DETECT_BAUDRATE_ERROR = (URG3D_COMMON_ERROR_LAST -1) -2,
    URG3D_ETHERNET_OPEN_ERROR = (URG3D_COMMON_ERROR_LAST -1) -3,
    URG3D_SCANNING_PARAMETER_ERROR = (URG3D_COMMON_ERROR_LAST -1) -4,
    URG3D_DATA_SIZE_PARAMETER_ERROR = (URG3D_COMMON_ERROR_LAST -1) -5,
};

#endif /* !URG3D_ERRNO_H */
